In [ ]:
#Getting data from yfinance

In [3]:
import yfinance as yf
import numpy as np
import matplotlib as plt

ticker = yf.Ticker('MSFT') #change stock ticker here
ticker_history = ticker.history(start='2024-01-01', end='2024-01-11', interval="1d") 
volume = ticker.info["averageVolume10days"]

ticker_history.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-01-02 00:00:00-05:00,371.085015,373.109882,364.047644,368.117218,25258600,0.0,0.0
2024-01-03 00:00:00-05:00,366.271079,370.489534,365.774790,367.849274,23083500,0.0,0.0
2024-01-04 00:00:00-05:00,367.918763,370.330719,364.444741,365.209015,20901500,0.0,0.0
2024-01-05 00:00:00-05:00,366.231362,369.298423,363.779694,365.020416,20987000,0.0,0.0
2024-01-08 00:00:00-05:00,366.558897,372.415129,366.271072,371.908905,23134000,0.0,0.0